/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "timetracker_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TimetrackerAdaptor
 */

TimetrackerAdaptor::TimetrackerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TimetrackerAdaptor::~TimetrackerAdaptor()
{
    // destructor
}

void TimetrackerAdaptor::startTracking()
{
    // handle method call org.f5n.timetracker.startTracking
    QMetaObject::invokeMethod(parent(), "startTracking");
}

void TimetrackerAdaptor::stopTracking()
{
    // handle method call org.f5n.timetracker.stopTracking
    QMetaObject::invokeMethod(parent(), "stopTracking");
}

