/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a timetracker_adaptor.h: timetracker.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TIMETRACKER_ADAPTOR_H
#define TIMETRACKER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.f5n.timetracker
 */
class TimetrackerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.f5n.timetracker")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.f5n.timetracker\">\n"
"    <method name=\"startTracking\"/>\n"
"    <method name=\"stopTracking\"/>\n"
"    <method name=\"resetTracking\"/>\n"
"    <method name=\"toggleWindow\"/>\n"
"    <method name=\"getElapsedSeconds\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"response\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TimetrackerAdaptor(QObject *parent);
    virtual ~TimetrackerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int getElapsedSeconds();
    void resetTracking();
    void startTracking();
    void stopTracking();
    void toggleWindow();
Q_SIGNALS: // SIGNALS
};

#endif
